### ISSUE TITLE
research: ALFRED package

### ISSUE THREAD

**Issue by mbannert** [opentsi/deloRean#5]
in-depth research of 

- [x] function interface (functions + parameters + output) 
- [x] data documentation
- [x] vintages output (how does ALFRED handle output)

**Comment by minnaheim** [comment]
Alfred doesn't have much data documentation - I assume this is because to get the series you need the ID of the time series, which is found on the (al)fred website, where all information is contained. 

For reference, other time series (data) packages (forecast) are better documented, i.e. when calling ?gas ?gold you can see the series descriptions, but no sources listed

-> for us:  readme as data description, with minimum: data source, variable names/description?

**Comment by minnaheim** [comment]
regarding the vintages:

```{r}
library(alfred)
indpro <- get_alfred_series("INDPRO", observation_start = "2000-01-01", realtime_start = "2000-01-01")

> tail(indpro)
            date realtime_period   INDPRO
92899 2024-01-01      2024-07-17 101.4830
92900 2024-02-01      2024-07-17 102.6045
92901 2024-03-01      2024-07-17 102.4062
92902 2024-04-01      2024-07-17 102.4329
92903 2024-05-01      2024-07-17 103.3282
92904 2024-06-01      2024-07-17 103.9941
```
The structure of the vintages is that each time series is repeated entirely for each version. Aka: for the version 2024-07-17, the entire indpro values are repeated from the start of the series till the date of the version (2024-07-17 here).

**Comment by minnaheim** [comment]
to properly address the issue, I created a new `research` branch on which I went through a basic time series analysis, by using Alfred time series data incl. two versions, and then added more details to the answers from above in the commit 0036bdb and potential suggestions for opentsi/deloRean.
